from monkeylearn import MonkeyLearn

ml = MonkeyLearn('afa2f7cb7cd8cc80cd152db15ceea8eccd1330aa')
data = ["""CORYDON, Ind., April 27, 2020 (GLOBE NEWSWIRE) -- First Capital, Inc. (the “Company”) (NASDAQ:  FCAP), the holding company for First Harrison Bank (the “Bank”), today reported net income of $2.1 million or $0.63 per diluted share for the quarter ended March 31, 2020, compared to $2.1 million or $0.64 per diluted share for the quarter ended March 31, 2019.  Net income remained flat despite an increase in net interest income after provision for loan losses due to a decrease in noninterest income and an increase in noninterest expense.

Net interest income after provision for loan losses increased $103,000 for the quarter ended March 31, 2020 as compared to the same period in 2019.  Interest income increased $16,000 when comparing the periods due to an increase in the average balance of interest-earning assets from $741.0 million for the first quarter of 2019 to $761.7 million for the first quarter of 2020 partially offset by a decrease in the average tax-equivalent yield on interest-earning assets from 4.19% for the first quarter of 2019 to 4.10% for the first quarter of 2020.  Interest expense increased $12,000 when comparing the periods due to an increase in the average balance of interest-bearing liabilities from $558.6 million for the first quarter of 2019 to $571.2 million for the first quarter of 2020.  The average cost of interest-bearing liabilities remained 0.33% during each of the two periods.  As a result of the changes in interest-earning assets and interest-bearing liabilities, the interest rate spread decreased from 3.86% for the quarter ended March 31, 2019 to 3.77% for the same period in 2020. 

Based on management’s analysis of the allowance for loan losses, the provision for loan losses decreased from $450,000 for the quarter ended March 31, 2019 to $351,000 for the quarter ended March 31, 2020.  During the three-month period ended March 31, 2019, net loans receivable increased $15.5 million and net charge-offs totaled $176,000 compared to a decrease in net loans receivable of $1.2 million and net charge-offs of $105,000 during the same period in 2020.  The $351,000 provision during 2020 primarily reflects changes to qualitative factors within the Bank’s allowance for loan losses calculation related to uncertainties surrounding COVID-19.  While it is too early to know the full extent of potential future losses associated with the impact of COVID-19, the Bank continues to monitor the situation and may need to adjust future expectations as developments occur throughout the remainder of the year.    

Noninterest income decreased $49,000 for the quarter ended March 31, 2020 as compared to the same period in 2019.  The first quarter of 2020 included a $394,000 unrealized loss on equity securities compared to a $131,000 unrealized gain on equity securities during the same period in 2019.  Gains on the sale of loans and ATM and debit card fees increased $201,000 and $118,000, respectively, when comparing the two periods. 

Noninterest expense increased $160,000 for the quarter ended March 31, 2020 as compared to the same period in 2019, due primarily to an increase in compensation and benefits expense of $460,000 partially offset by a decrease in net losses on foreclosed real estate of $194,000.

Income tax expense decreased $53,000 for the first quarter of 2020 as compared to the first quarter of 2019 primarily due to an increase in nontaxable income.   As a result, the effective tax rate for the quarter ended March 31, 2020 was 15.6% compared to 17.1% for the same period in 2019.   

Total assets increased $3.7 million to $831.2 million at March 31, 2020 from $827.5 million at December 31, 2019.  Cash and cash equivalents increased $8.4 million from December 31, 2019 to March 31, 2020 while investment securities, net loans receivable and loans held for sale decreased $1.4 million, $1.2 million and $1.1 million, respectively.  Deposits increased $441,000 at March 31, 2020.  Nonperforming assets (consisting of nonaccrual loans, accruing loans 90 days or more past due, troubled debt restructurings on accrual status, and foreclosed real estate) decreased from $3.1 million at December 31, 2019 to $3.0 million at March 31, 2020.  The Bank is assisting its customers experiencing a COVID-19 related hardship by approving payment extensions and waiving or refunding certain banking fees.  As of April 24, 2020, the Bank has approved such extensions on approximately 10.8% of balances in the loan portfolio, primarily related to commercial real estate lending relationships.  Additionally, the Bank is participating in the Small Business Administration’s Paycheck Protection Program (PPP), and as has approved approximately $35.1 million of PPP loans as of April 24, 2020."""]
model_id = 'cl_pi3C7JiL'
result = ml.classifiers.classify(model_id, data)
print(result.body)